name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the version
      id: vars
      run: echo ::set-output name=sha::$(echo ${GITHUB_SHA::8})
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USER }}
        KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha }}
      run: |
        # The SSH key needs to be saved to a file for SSH to use
        echo "$KEY" > ec2-key.pem
        chmod 400 ec2-key.pem
        # SSH into the EC2 instance, pull the latest image, and restart the Docker service
        ssh -i ec2-key.pem -o "StrictHostKeyChecking=no" $USERNAME@$HOST << EOF
          cd Portal && docker-compose pull && docker-compose up -d
        EOF
